kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: noppawit/rpi-nginx-certbot-cloudflare
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
